[package]
name = "serial_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
postcard = "1.0.2"
serialport = "4.2.0"
